version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # environment:
    #   - NODE_ENV=production
    #   - PORT=8080
    restart: always
    external_links:
      - mongo

  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongo_db:/data/db
volumes:
  mongo_db: {}

